#ifndef ATLAS_COMMON_ATLAS_CONFIG_H
#define ATLAS_COMMON_ATLAS_CONFIG_H

#define DEBUG

#define JOINTS_DELTA_TIMER_TIMEOUT_S (0.01F)

typedef enum {
    JOINT_NUM_1,
    JOINT_NUM_2,
    JOINT_NUM_3,
    JOINT_NUM_4,
    JOINT_NUM_5,
    JOINT_NUM_6,
    JOINT_NUM,
} joint_num_t;

#endif // ATLAS_COMMON_ATLAS_CONFIG_H