#ifndef ATLAS_KINEMATICS_MANAGER_KINEMATICS_MANAGER_H
#define ATLAS_KINEMATICS_MANAGER_KINEMATICS_MANAGER_H

typedef enum {
    KINEMATICS_ERR_OK,
} kinematics_err_t;

#endif // ATLAS_KINEMATICS_MANAGER_KINEMATICS_MANAGER_H